### ISSUE TITLE
屮

### ISSUE THREAD

**Issue by iSudocat** [wzytim/android-photo-time-reset#1]
txt 不行

**Comment by Mr-Tim-CN** [comment]
？干嘛呢


---原始邮件---
发件人: &quot;Sudocat&quot;<notifications@github.com&gt;
发送时间: 2021年2月7日(周日) 晚上7:33
收件人: &quot;wzytim/android-photo-time-reset&quot;<android-photo-time-reset@noreply.github.com&gt;;
抄送: &quot;Subscribed&quot;<subscribed@noreply.github.com&gt;;
主题: [wzytim/android-photo-time-reset] 屮 (#1)




 
txt 不行
 
&mdash;

**Comment by iSudocat** [comment]
字 面 意 思

**Comment by Mr-Tim-CN** [comment]
又不是不能看.jpg


---原始邮件---
发件人: &quot;Sudocat&quot;<notifications@github.com&gt;
发送时间: 2021年2月7日(周日) 晚上7:35
收件人: &quot;wzytim/android-photo-time-reset&quot;<android-photo-time-reset@noreply.github.com&gt;;
抄送: &quot;wzytim&quot;<690723857@qq.com&gt;;&quot;Comment&quot;<comment@noreply.github.com&gt;;
主题: Re: [wzytim/android-photo-time-reset] 屮 (#1)




 
字 面 意 思
 
&mdash;
